# Generated by Django 5.2.11 on 2026-02-21 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('working_hours', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('caffeine', models.FloatField()),
                ('job_satisfaction', models.IntegerField()),
                ('mental_health_score', models.FloatField(blank=True, null=True)),
                ('predicted_stress', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
