# Generated by Django 5.2.11 on 2026-02-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0002_employeeprofile_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
