# Generated by Django 5.2.11 on 2026-02-22 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0003_employeeprofile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours_per_week', models.FloatField()),
                ('remote_work', models.BooleanField()),
                ('workload_score', models.FloatField()),
                ('job_satisfaction', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('physical_activity_hrs', models.FloatField()),
                ('caffeine_intake', models.FloatField()),
                ('stress_level', models.FloatField()),
                ('mental_health_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
