# Generated by Django 5.2.11 on 2026-02-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0004_stressrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stressrecord',
            name='remote_work',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('PM', 'Project Manager'), ('EMP', 'Employee')], default='EMP', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_hours_per_week', models.FloatField()),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stressapp.employeeprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stressapp.project')),
            ],
        ),
    ]
