# Generated by Django 5.2.11 on 2026-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0005_remove_stressrecord_remote_work_employeeprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_employees',
            field=models.IntegerField(default=5),
        ),
    ]
