# Generated by Django 5.2.11 on 2026-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0006_project_max_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
