# Generated by Django 5.2.11 on 2026-03-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0007_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectallocation',
            unique_together={('employee', 'project')},
        ),
    ]
