# Generated by Django 5.2.11 on 2026-03-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0008_alter_projectallocation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectallocation',
            name='task_role',
            field=models.CharField(choices=[('UI/UX', 'UI/UX'), ('Database Design', 'Database Design'), ('Backend Developer', 'Backend Developer'), ('Requirement Gathering', 'Requirement Gathering'), ('Testing', 'Testing')], default='UIUX', max_length=50),
            preserve_default=False,
        ),
    ]
