# Generated by Django 5.2.11 on 2026-03-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0009_projectallocation_task_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectallocation',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
