# Generated by Django 5.2.11 on 2026-03-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0010_projectallocation_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_employees',
            field=models.IntegerField(),
        ),
    ]
