# Generated by Django 5.2.11 on 2026-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0011_alter_project_max_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='stressrecord',
            name='remote_work',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stressrecord',
            name='work_experience',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
